version: 0.0
os: linux

files:
  - source: /java-tomcat-maven-example.war
    destination: /var/lib/tomcat10/webapps/
    
file_exists_behavior: OVERWRITE    
          
hooks:
  AfterInstall:
    - location: scripts/server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 300
      runas: root 
