
version: 0.0
os: linux

files:
  - source: /java-tomcat-maven-example.war
    destination: /var/lib/tomcat10/webapps/
  - source: /server_start.sh
    destination: /var/lib/tomcat10/webapps/
  - source: /server_stop.sh
    destination: /var/lib/tomcat10/webapps/

   
file_exists_behavior: OVERWRITE    
          
hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root
